In [1]:
!jupyter nbextension enable --py widgetsnbextension

Enabling notebook extension jupyter-js-widgets/extension...
      - Validating: ok

In [1]:
from api.weather import awhere
from datetime import datetime

In [2]:
module = awhere.AWhere(key = "*****", secret = "*****")

In [3]:
# getting data for 2017 example with grid
module.get_observations_by_grid(bottom=4, top=4.5, left=34.7, right = 35, 
                                resolution = 0.075, 
                                from_date = datetime(2017,1,1), 
                                to_date = datetime(2018,1,1), 
                                to_file = True)

Processing lattitude: 4.0: 100%|█████████████████████████████████████████████████████████| 5/5 [01:04<00:00, 13.06s/it]
Processing lattitude: 4.075: 100%|███████████████████████████████████████████████████████| 5/5 [01:02<00:00, 12.51s/it]
Processing lattitude: 4.15: 100%|████████████████████████████████████████████████████████| 5/5 [01:02<00:00, 12.65s/it]
Processing lattitude: 4.2250000000000005: 100%|██████████████████████████████████████████| 5/5 [01:01<00:00, 12.41s/it]
Processing lattitude: 4.300000000000001: 100%|███████████████████████████████████████████| 5/5 [01:03<00:00, 12.71s/it]
Processing lattitude: 4.375000000000001: 100%|███████████████████████████████████████████| 5/5 [01:04<00:00, 12.85s/it]
Processing lattitude: 4.450000000000001: 100%|███████████████████████████████████████████| 5/5 [01:04<00:00, 12.79s/it]
Processing lattitude: 4.525000000000001: 100%|███████████████████████████████████████████| 5/5 [01:02<00:00, 12.56s/it]

,date,lat,lon,temp_min,temp_max,precipitation,solar,relative_humidity_min,relative_humidity_max,wind_morning_max,wind_day_max,wind_average
0,2017-01-01,4.000,34.700001,21.440001,34.349998,0.000000,4699.759766,44.419998,64.449997,8.636424,9.677523,3.780711
1,2017-01-02,4.000,34.700001,19.870001,35.180000,0.000000,4591.219238,35.650002,75.139999,6.266512,9.197930,3.217510
2,2017-01-03,4.000,34.700001,25.110001,36.990002,0.000000,7078.051270,24.010000,86.900002,7.321171,8.854383,3.915653
3,2017-01-04,4.000,34.700001,23.510000,37.700001,0.000000,6977.279785,30.430000,59.090000,7.364702,8.612165,4.501485
4,2017-01-05,4.000,34.700001,23.969999,36.910000,0.000000,6926.962891,33.419998,76.720001,7.260920,9.190339,4.418503
5,2017-01-06,4.000,34.700001,23.680000,37.950001,0.000000,7233.404785,33.430000,75.860001,6.612383,8.205201,3.617803
6,2017-01-07,4.000,34.700001,23.230000,37.880001,0.000000,6275.777832,23.430000,67.379997,4.696296,7.405700,3.091669
7,2017-01-08,4.000,34.700001,21.840000,37.230000,0.000000,5596.426758,27.180000,68.050003,4.266193,6.976645,2.991915
8,2017-01-09,4.000,34.700001,20.930000,37.400002,0.000000,6537.832520,25.120001,69.980003,5.021259,7.924963,2.867205
9,2017-01-10,4.000,34.700001,22.440001,35.849998,0.000000,6042.104004,33.459999,66.139999,6.736399,8.286771,3.875614
10,2017-01-11,4.000,34.700001,23.160000,36.680000,0.000000,5634.214844,39.910000,68.230003,6.416273,7.680522,4.573048
11,2017-01-12,4.000,34.700001,25.299999,35.910000,0.000000,7206.498535,14.360000,80.669998,7.304100,7.898442,4.337945
12,2017-01-13,4.000,34.700001,23.809999,37.410000,0.000000,6522.577637,33.299999,80.389999,5.144779,7.194842,3.332613
13,2017-01-14,4.000,34.700001,22.620001,37.720001,0.000000,5491.306641,39.730000,83.540001,5.277817,5.796337,2.737242
14,2017-01-15,4.000,34.700001,24.290001,38.730000,0.000000,6801.282715,19.240000,67.059998,5.413164,7.649963,4.283169
15,2017-01-16,4.000,34.700001,26.139999,38.310001,0.000000,7260.597656,14.760000,64.769997,5.886511,8.768605,4.091872
16,2017-01-17,4.000,34.700001,25.920000,37.880001,0.000000,7389.063477,38.959999,71.000000,7.377688,8.701823,4.575171
17,2017-01-18,4.000,34.700001,25.690001,37.349998,0.000000,6123.383301,25.340000,60.849998,7.546210,8.882524,4.405563
18,2017-01-19,4.000,34.700001,24.040001,37.470001,0.000000,6007.371094,25.480000,65.519997,5.297513,7.402396,3.463936
19,2017-01-20,4.000,34.700001,23.370001,37.669998,0.000000,5618.412109,45.349998,67.739998,5.451696,7.314089,2.965646
20,2017-01-21,4.000,34.700001,24.889999,38.599998,0.000000,5584.004395,39.430000,72.150002,6.356426,7.703335,3.769284
21,2017-01-22,4.000,34.700001,24.870001,38.549999,0.000000,5866.096680,36.310001,71.519997,8.357899,8.704806,4.872842
22,2017-01-23,4.000,34.700001,21.549999,38.410000,0.000000,6458.832031,32.580002,75.250000,7.102396,8.360652,4.723850
23,2017-01-24,4.000,34.700001,23.530001,37.930000,0.000000,6808.813477,14.800000,77.459999,7.307455,8.559834,4.525402
24,2017-01-25,4.000,34.700001,23.670000,38.430000,0.000000,6619.942871,36.439999,69.580002,7.776928,9.452873,3.823743
25,2017-01-26,4.000,34.700001,25.040001,37.709999,0.000000,5763.042480,32.029999,71.209999,8.735942,10.436982,3.676231
26,2017-01-27,4.000,34.700001,24.910000,38.380001,0.000000,6199.560547,40.570000,69.769997,5.747393,8.498998,3.527933
27,2017-01-28,4.000,34.700001,24.889999,37.919998,0.000000,5253.232422,32.169998,70.660004,5.192638,8.876561,3.291211
28,2017-01-29,4.000,34.700001,25.480000,34.790001,8.187710,4482.072266,57.849998,82.230003,5.437307,7.090517,3.389646
29,2017-01-30,4.000,34.700001,24.740000,34.520000,1.566667,5064.974609,44.840000,84.220001,4.580123,7.030896,2.619622
...,...,...,...,...,...,...,...,...,...,...,...,...
14610,2017-12-03,4.525,35.000000,22.639999,37.310001,0.000000,5442.847168,36.799999,76.639999,4.415306,5.747030,2.932309
14611,2017-12-04,4.525,35.000000,23.480000,37.029999,0.000000,5970.909180,36.810001,82.440002,4.692642,5.611100,3.269910
14612,2017-12-05,4.525,35.000000,22.260000,37.750000,0.000000,5753.062500,47.549999,80.139999,4.523479,5.258777,2.758619
14613,2017-12-06,4.525,35.000000,23.840000,37.290001,0.000000,5035.667480,50.410000,85.709999,4.289799,6.210618,2.898477
14614,2017-12-07,4.525,35.000000,27.309999,36.430000,0.000000,4214.780762,56.650002,78.739998,4.815447,5.306039,2.703185
14615,2017-12-08,4.525,35.000000,24.360001,36.330002,0.000000,4824.946289,46.259998,81.699997,5.783430,6.916209,3.425618
14616,2017-12-09,4.525,35.000000,20.980000,36.200001,0.000000,4621.180664,56.869999,91.070000,5.812492,5.940091,4.292561
14617,2017-12-10,4.525,35.000000,20.790001,36.470001,0.000000,4983.111816,32.049999,79.000000,5.411667,6.137509,4.137199
14618,2017-12-11,4.525,35.000000,21.100000,35.820000,0.000000,5118.396973,37.810001,77.309998,5.121288,5.957956,3.704377
14619,2017-12-12,4.525,35.000000,22.070000,36.209999,0.000000,6385.604492,40.369999,70.760002,5.880666,7.114058,3.776519
14620,2017-12-13,4.525,35.000000,20.910000,36.080002,0.000000,6082.898438,39.160000,73.540001,4.774163,5.910357,2.804632
14621,2017-12-14,4.525,35.000000,21.950001,36.410000,0.000000,4541.232422,37.750000,67.190002,3.153874,4.436706,2.430493
14622,2017-12-15,4.525,35.000000,22.450001,37.630001,0.000000,5517.028320,51.139999,68.449997,3.508113,5.332092,2.820082
14623,2017-12-16,4.525,35.000000,23.620001,37.650002,0.000000,6124.309082,49.730000,71.430000,4.888599,6.760605,3.605947
14624,2017-12-17,4.525,35.000000,24.200001,36.230000,0.000000,5452.948730,32.980000,73.580002,4.867858,6.541091,3.165041
14625,2017-12-18,4.525,35.000000,25.100000,36.959999,0.000000,6118.507812,46.189999,81.360001,6.631529,7.509321,4.760140
14626,2017-12-19,4.525,35.000000,23.370001,36.099998,0.000000,5347.333008,45.130001,78.430000,7.058200,7.733512,4.852036
14627,2017-12-20,4.525,35.000000,22.600000,36.570000,0.000000,5871.553223,30.320000,92.419998,6.661877,7.093603,4.701143
14628,2017-12-21,4.525,35.000000,23.690001,35.990002,0.000000,6192.553711,31.480000,73.680000,7.237388,8.020021,4.577760
14629,2017-12-22,4.525,35.000000,22.110001,35.939999,0.000000,6296.166504,38.840000,78.650002,6.119148,6.574173,3.737257
14630,2017-12-23,4.525,35.000000,22.120001,35.439999,0.000000,6490.235840,45.380001,67.440002,6.154061,6.759822,4.263012
14631,2017-12-24,4.525,35.000000,21.110001,36.000000,0.000000,5604.752441,26.920000,71.589996,4.832164,5.700435,3.296407
14632,2017-12-25,4.525,35.000000,23.660000,37.209999,0.000000,4810.552246,26.129999,63.389999,4.195321,4.712702,3.136930
14633,2017-12-26,4.525,35.000000,21.910000,37.669998,0.000000,6007.587891,19.120001,53.830002,4.666553,6.258623,4.041260
14634,2017-12-27,4.525,35.000000,23.090000,37.139999,0.000000,6261.083008,32.259998,72.500000,5.384336,6.641347,3.760065
14635,2017-12-28,4.525,35.000000,21.809999,36.910000,0.000000,5875.360840,19.780001,77.980003,5.827936,8.300435,3.713354
14636,2017-12-29,4.525,35.000000,22.139999,36.880001,0.000000,5349.820312,30.430000,77.639999,4.931769,6.173853,3.105559
14637,2017-12-30,4.525,35.000000,22.139999,36.770000,0.000000,5006.813965,30.290001,70.959999,5.489073,6.837867,3.174361
14638,2017-12-31,4.525,35.000000,22.170000,36.320000,0.000000,4697.683105,38.590000,76.870003,4.264045,6.158151,2.819854
14639,2018-01-01,4.525,35.000000,22.799999,36.450001,0.000000,4747.577637,38.770000,76.820000,4.422494,5.770876,2.600995

In [1]:
import os
from collections import namedtuple
import pandas as pd
import numpy as np
import json
from datetime import datetime
from modules.api.weather import awhere
os.getcwd()

'C:\\Users\\Denys\\Desktop\\Projects\\Viamo-Recommendation\\weathermodule'

In [2]:
module = awhere.AWhere(key = "****", secret = "****")

In [ ]:
# example with geojson file
module.get_by_country(country='uganda', from_date = datetime(2018,1,1), to_date = datetime(2018,12,31), forecast = False, to_file = True)

  2%|█▌                                                                           | 73/3485 [15:42<11:54:25, 12.56s/it]

In [3]:
module.generate_grid(top=4.5, bottom=-2, left = 29, right = 32)

[Point(lon=29.0, lat=-2.0),
 Point(lon=29.25, lat=-2.0),
 Point(lon=29.5, lat=-2.0),
 Point(lon=29.75, lat=-2.0),
 Point(lon=30.0, lat=-2.0),
 Point(lon=30.25, lat=-2.0),
 Point(lon=30.5, lat=-2.0),
 Point(lon=30.75, lat=-2.0),
 Point(lon=31.0, lat=-2.0),
 Point(lon=31.25, lat=-2.0),
 Point(lon=31.5, lat=-2.0),
 Point(lon=31.75, lat=-2.0),
 Point(lon=32.0, lat=-2.0),
 Point(lon=29.0, lat=-1.75),
 Point(lon=29.25, lat=-1.75),
 Point(lon=29.5, lat=-1.75),
 Point(lon=29.75, lat=-1.75),
 Point(lon=30.0, lat=-1.75),
 Point(lon=30.25, lat=-1.75),
 Point(lon=30.5, lat=-1.75),
 Point(lon=30.75, lat=-1.75),
 Point(lon=31.0, lat=-1.75),
 Point(lon=31.25, lat=-1.75),
 Point(lon=31.5, lat=-1.75),
 Point(lon=31.75, lat=-1.75),
 Point(lon=32.0, lat=-1.75),
 Point(lon=29.0, lat=-1.5),
 Point(lon=29.25, lat=-1.5),
 Point(lon=29.5, lat=-1.5),
 Point(lon=29.75, lat=-1.5),
 Point(lon=30.0, lat=-1.5),
 Point(lon=30.25, lat=-1.5),
 Point(lon=30.5, lat=-1.5),
 Point(lon=30.75, lat=-1.5),
 Point(lon=31.0, lat=-1.5),
 Point(lon=31.25, lat=-1.5),
 Point(lon=31.5, lat=-1.5),
 Point(lon=31.75, lat=-1.5),
 Point(lon=32.0, lat=-1.5),
 Point(lon=29.0, lat=-1.25),
 Point(lon=29.25, lat=-1.25),
 Point(lon=29.5, lat=-1.25),
 Point(lon=29.75, lat=-1.25),
 Point(lon=30.0, lat=-1.25),
 Point(lon=30.25, lat=-1.25),
 Point(lon=30.5, lat=-1.25),
 Point(lon=30.75, lat=-1.25),
 Point(lon=31.0, lat=-1.25),
 Point(lon=31.25, lat=-1.25),
 Point(lon=31.5, lat=-1.25),
 Point(lon=31.75, lat=-1.25),
 Point(lon=32.0, lat=-1.25),
 Point(lon=29.0, lat=-1.0),
 Point(lon=29.25, lat=-1.0),
 Point(lon=29.5, lat=-1.0),
 Point(lon=29.75, lat=-1.0),
 Point(lon=30.0, lat=-1.0),
 Point(lon=30.25, lat=-1.0),
 Point(lon=30.5, lat=-1.0),
 Point(lon=30.75, lat=-1.0),
 Point(lon=31.0, lat=-1.0),
 Point(lon=31.25, lat=-1.0),
 Point(lon=31.5, lat=-1.0),
 Point(lon=31.75, lat=-1.0),
 Point(lon=32.0, lat=-1.0),
 Point(lon=29.0, lat=-0.75),
 Point(lon=29.25, lat=-0.75),
 Point(lon=29.5, lat=-0.75),
 Point(lon=29.75, lat=-0.75),
 Point(lon=30.0, lat=-0.75),
 Point(lon=30.25, lat=-0.75),
 Point(lon=30.5, lat=-0.75),
 Point(lon=30.75, lat=-0.75),
 Point(lon=31.0, lat=-0.75),
 Point(lon=31.25, lat=-0.75),
 Point(lon=31.5, lat=-0.75),
 Point(lon=31.75, lat=-0.75),
 Point(lon=32.0, lat=-0.75),
 Point(lon=29.0, lat=-0.5),
 Point(lon=29.25, lat=-0.5),
 Point(lon=29.5, lat=-0.5),
 Point(lon=29.75, lat=-0.5),
 Point(lon=30.0, lat=-0.5),
 Point(lon=30.25, lat=-0.5),
 Point(lon=30.5, lat=-0.5),
 Point(lon=30.75, lat=-0.5),
 Point(lon=31.0, lat=-0.5),
 Point(lon=31.25, lat=-0.5),
 Point(lon=31.5, lat=-0.5),
 Point(lon=31.75, lat=-0.5),
 Point(lon=32.0, lat=-0.5),
 Point(lon=29.0, lat=-0.25),
 Point(lon=29.25, lat=-0.25),
 Point(lon=29.5, lat=-0.25),
 Point(lon=29.75, lat=-0.25),
 Point(lon=30.0, lat=-0.25),
 Point(lon=30.25, lat=-0.25),
 Point(lon=30.5, lat=-0.25),
 Point(lon=30.75, lat=-0.25),
 Point(lon=31.0, lat=-0.25),
 Point(lon=31.25, lat=-0.25),
 Point(lon=31.5, lat=-0.25),
 Point(lon=31.75, lat=-0.25),
 Point(lon=32.0, lat=-0.25),
 Point(lon=29.0, lat=0.0),
 Point(lon=29.25, lat=0.0),
 Point(lon=29.5, lat=0.0),
 Point(lon=29.75, lat=0.0),
 Point(lon=30.0, lat=0.0),
 Point(lon=30.25, lat=0.0),
 Point(lon=30.5, lat=0.0),
 Point(lon=30.75, lat=0.0),
 Point(lon=31.0, lat=0.0),
 Point(lon=31.25, lat=0.0),
 Point(lon=31.5, lat=0.0),
 Point(lon=31.75, lat=0.0),
 Point(lon=32.0, lat=0.0),
 Point(lon=29.0, lat=0.25),
 Point(lon=29.25, lat=0.25),
 Point(lon=29.5, lat=0.25),
 Point(lon=29.75, lat=0.25),
 Point(lon=30.0, lat=0.25),
 Point(lon=30.25, lat=0.25),
 Point(lon=30.5, lat=0.25),
 Point(lon=30.75, lat=0.25),
 Point(lon=31.0, lat=0.25),
 Point(lon=31.25, lat=0.25),
 Point(lon=31.5, lat=0.25),
 Point(lon=31.75, lat=0.25),
 Point(lon=32.0, lat=0.25),
 Point(lon=29.0, lat=0.5),
 Point(lon=29.25, lat=0.5),
 Point(lon=29.5, lat=0.5),
 Point(lon=29.75, lat=0.5),
 Point(lon=30.0, lat=0.5),
 Point(lon=30.25, lat=0.5),
 Point(lon=30.5, lat=0.5),
 Point(lon=30.75, lat=0.5),
 Point(lon=31.0, lat=0.5),
 Point(lon=31.25, lat=0.5),
 Point(lon=31.5, lat=0.5),
 Point(lon=31.75, lat=0.5),
 Point(lon=32.0, lat=0.5),
 Point(lon=29.0, lat=0.75),
 Point(lon=29.25, lat=0.75),
 Point(lon=29.5, lat=0.75),
 Point(lon=29.75, lat=0.75),
 Point(lon=30.0, lat=0.75),
 Point(lon=30.25, lat=0.75),
 Point(lon=30.5, lat=0.75),
 Point(lon=30.75, lat=0.75),
 Point(lon=31.0, lat=0.75),
 Point(lon=31.25, lat=0.75),
 Point(lon=31.5, lat=0.75),
 Point(lon=31.75, lat=0.75),
 Point(lon=32.0, lat=0.75),
 Point(lon=29.0, lat=1.0),
 Point(lon=29.25, lat=1.0),
 Point(lon=29.5, lat=1.0),
 Point(lon=29.75, lat=1.0),
 Point(lon=30.0, lat=1.0),
 Point(lon=30.25, lat=1.0),
 Point(lon=30.5, lat=1.0),
 Point(lon=30.75, lat=1.0),
 Point(lon=31.0, lat=1.0),
 Point(lon=31.25, lat=1.0),
 Point(lon=31.5, lat=1.0),
 Point(lon=31.75, lat=1.0),
 Point(lon=32.0, lat=1.0),
 Point(lon=29.0, lat=1.25),
 Point(lon=29.25, lat=1.25),
 Point(lon=29.5, lat=1.25),
 Point(lon=29.75, lat=1.25),
 Point(lon=30.0, lat=1.25),
 Point(lon=30.25, lat=1.25),
 Point(lon=30.5, lat=1.25),
 Point(lon=30.75, lat=1.25),
 Point(lon=31.0, lat=1.25),
 Point(lon=31.25, lat=1.25),
 Point(lon=31.5, lat=1.25),
 Point(lon=31.75, lat=1.25),
 Point(lon=32.0, lat=1.25),
 Point(lon=29.0, lat=1.5),
 Point(lon=29.25, lat=1.5),
 Point(lon=29.5, lat=1.5),
 Point(lon=29.75, lat=1.5),
 Point(lon=30.0, lat=1.5),
 Point(lon=30.25, lat=1.5),
 Point(lon=30.5, lat=1.5),
 Point(lon=30.75, lat=1.5),
 Point(lon=31.0, lat=1.5),
 Point(lon=31.25, lat=1.5),
 Point(lon=31.5, lat=1.5),
 Point(lon=31.75, lat=1.5),
 Point(lon=32.0, lat=1.5),
 Point(lon=29.0, lat=1.75),
 Point(lon=29.25, lat=1.75),
 Point(lon=29.5, lat=1.75),
 Point(lon=29.75, lat=1.75),
 Point(lon=30.0, lat=1.75),
 Point(lon=30.25, lat=1.75),
 Point(lon=30.5, lat=1.75),
 Point(lon=30.75, lat=1.75),
 Point(lon=31.0, lat=1.75),
 Point(lon=31.25, lat=1.75),
 Point(lon=31.5, lat=1.75),
 Point(lon=31.75, lat=1.75),
 Point(lon=32.0, lat=1.75),
 Point(lon=29.0, lat=2.0),
 Point(lon=29.25, lat=2.0),
 Point(lon=29.5, lat=2.0),
 Point(lon=29.75, lat=2.0),
 Point(lon=30.0, lat=2.0),
 Point(lon=30.25, lat=2.0),
 Point(lon=30.5, lat=2.0),
 Point(lon=30.75, lat=2.0),
 Point(lon=31.0, lat=2.0),
 Point(lon=31.25, lat=2.0),
 Point(lon=31.5, lat=2.0),
 Point(lon=31.75, lat=2.0),
 Point(lon=32.0, lat=2.0),
 Point(lon=29.0, lat=2.25),
 Point(lon=29.25, lat=2.25),
 Point(lon=29.5, lat=2.25),
 Point(lon=29.75, lat=2.25),
 Point(lon=30.0, lat=2.25),
 Point(lon=30.25, lat=2.25),
 Point(lon=30.5, lat=2.25),
 Point(lon=30.75, lat=2.25),
 Point(lon=31.0, lat=2.25),
 Point(lon=31.25, lat=2.25),
 Point(lon=31.5, lat=2.25),
 Point(lon=31.75, lat=2.25),
 Point(lon=32.0, lat=2.25),
 Point(lon=29.0, lat=2.5),
 Point(lon=29.25, lat=2.5),
 Point(lon=29.5, lat=2.5),
 Point(lon=29.75, lat=2.5),
 Point(lon=30.0, lat=2.5),
 Point(lon=30.25, lat=2.5),
 Point(lon=30.5, lat=2.5),
 Point(lon=30.75, lat=2.5),
 Point(lon=31.0, lat=2.5),
 Point(lon=31.25, lat=2.5),
 Point(lon=31.5, lat=2.5),
 Point(lon=31.75, lat=2.5),
 Point(lon=32.0, lat=2.5),
 Point(lon=29.0, lat=2.75),
 Point(lon=29.25, lat=2.75),
 Point(lon=29.5, lat=2.75),
 Point(lon=29.75, lat=2.75),
 Point(lon=30.0, lat=2.75),
 Point(lon=30.25, lat=2.75),
 Point(lon=30.5, lat=2.75),
 Point(lon=30.75, lat=2.75),
 Point(lon=31.0, lat=2.75),
 Point(lon=31.25, lat=2.75),
 Point(lon=31.5, lat=2.75),
 Point(lon=31.75, lat=2.75),
 Point(lon=32.0, lat=2.75),
 Point(lon=29.0, lat=3.0),
 Point(lon=29.25, lat=3.0),
 Point(lon=29.5, lat=3.0),
 Point(lon=29.75, lat=3.0),
 Point(lon=30.0, lat=3.0),
 Point(lon=30.25, lat=3.0),
 Point(lon=30.5, lat=3.0),
 Point(lon=30.75, lat=3.0),
 Point(lon=31.0, lat=3.0),
 Point(lon=31.25, lat=3.0),
 Point(lon=31.5, lat=3.0),
 Point(lon=31.75, lat=3.0),
 Point(lon=32.0, lat=3.0),
 Point(lon=29.0, lat=3.25),
 Point(lon=29.25, lat=3.25),
 Point(lon=29.5, lat=3.25),
 Point(lon=29.75, lat=3.25),
 Point(lon=30.0, lat=3.25),
 Point(lon=30.25, lat=3.25),
 Point(lon=30.5, lat=3.25),
 Point(lon=30.75, lat=3.25),
 Point(lon=31.0, lat=3.25),
 Point(lon=31.25, lat=3.25),
 Point(lon=31.5, lat=3.25),
 Point(lon=31.75, lat=3.25),
 Point(lon=32.0, lat=3.25),
 Point(lon=29.0, lat=3.5),
 Point(lon=29.25, lat=3.5),
 Point(lon=29.5, lat=3.5),
 Point(lon=29.75, lat=3.5),
 Point(lon=30.0, lat=3.5),
 Point(lon=30.25, lat=3.5),
 Point(lon=30.5, lat=3.5),
 Point(lon=30.75, lat=3.5),
 Point(lon=31.0, lat=3.5),
 Point(lon=31.25, lat=3.5),
 Point(lon=31.5, lat=3.5),
 Point(lon=31.75, lat=3.5),
 Point(lon=32.0, lat=3.5),
 Point(lon=29.0, lat=3.75),
 Point(lon=29.25, lat=3.75),
 Point(lon=29.5, lat=3.75),
 Point(lon=29.75, lat=3.75),
 Point(lon=30.0, lat=3.75),
 Point(lon=30.25, lat=3.75),
 Point(lon=30.5, lat=3.75),
 Point(lon=30.75, lat=3.75),
 Point(lon=31.0, lat=3.75),
 Point(lon=31.25, lat=3.75),
 Point(lon=31.5, lat=3.75),
 Point(lon=31.75, lat=3.75),
 Point(lon=32.0, lat=3.75),
 Point(lon=29.0, lat=4.0),
 Point(lon=29.25, lat=4.0),
 Point(lon=29.5, lat=4.0),
 Point(lon=29.75, lat=4.0),
 Point(lon=30.0, lat=4.0),
 Point(lon=30.25, lat=4.0),
 Point(lon=30.5, lat=4.0),
 Point(lon=30.75, lat=4.0),
 Point(lon=31.0, lat=4.0),
 Point(lon=31.25, lat=4.0),
 Point(lon=31.5, lat=4.0),
 Point(lon=31.75, lat=4.0),
 Point(lon=32.0, lat=4.0),
 Point(lon=29.0, lat=4.25),
 Point(lon=29.25, lat=4.25),
 Point(lon=29.5, lat=4.25),
 Point(lon=29.75, lat=4.25),
 Point(lon=30.0, lat=4.25),
 Point(lon=30.25, lat=4.25),
 Point(lon=30.5, lat=4.25),
 Point(lon=30.75, lat=4.25),
 Point(lon=31.0, lat=4.25),
 Point(lon=31.25, lat=4.25),
 Point(lon=31.5, lat=4.25),
 Point(lon=31.75, lat=4.25),
 Point(lon=32.0, lat=4.25),
 Point(lon=29.0, lat=4.5),
 Point(lon=29.25, lat=4.5),
 Point(lon=29.5, lat=4.5),
 Point(lon=29.75, lat=4.5),
 Point(lon=30.0, lat=4.5),
 Point(lon=30.25, lat=4.5),
 Point(lon=30.5, lat=4.5),
 Point(lon=30.75, lat=4.5),
 Point(lon=31.0, lat=4.5),
 Point(lon=31.25, lat=4.5),
 Point(lon=31.5, lat=4.5),
 Point(lon=31.75, lat=4.5),
 Point(lon=32.0, lat=4.5)]